source $ZSH_CUSTOM/_env.zsh
alias zshrc="source $HOME/.zshrc"
alias boardctl="sudo $L4T/tools/board_automation/boardctl -t topo"
alias tmux-resume="tmux attach-session -t \$(tmux list-sessions | head -1 | grep -Po '^.+?(?=:)')"
alias ssh-nocheck="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
alias scp-nocheck="scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
alias ngrok-auto-hide="/home/ubu/ngrok-automation/.venv/bin/python /home/ubu/ngrok-automation/ngrok-automation.py > /dev/null &!"
alias ngrok-auto="/home/ubu/ngrok-automation/.venv/bin/python /home/ubu/ngrok-automation/ngrok-automation.py"
alias mygpg="gpg -K | grep 'noah.wager@canonical.com' -B1 | head -n1 | tr -d ' '"
alias myssh="cat ~/.ssh/id_ed25519.pub"
